# Generated by Django 3.1.2 on 2020-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Executive Committee', 'Executive Committee'), ('Advisors', 'Advisors'), ('Members', 'Members')], max_length=25)),
            ],
        ),
    ]
