# Generated by Django 3.1.2 on 2020-10-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=500)),
                ('organiser', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
