# Generated by Django 3.1.2 on 2020-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='filled_form',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='title',
        ),
        migrations.AddField(
            model_name='membership',
            name='email',
            field=models.CharField(default='Test', max_length=250),
        ),
        migrations.AddField(
            model_name='membership',
            name='family_name',
            field=models.CharField(default='Test', max_length=150),
        ),
        migrations.AddField(
            model_name='membership',
            name='first_name',
            field=models.CharField(default='Test', max_length=150),
        ),
        migrations.AddField(
            model_name='membership',
            name='name1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='name3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='phone',
            field=models.CharField(default='Test', max_length=15),
        ),
        migrations.AddField(
            model_name='membership',
            name='receipt',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='relation1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='relation2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='relation3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='state',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='street_name',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='street_no',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='membership',
            name='suburb',
            field=models.CharField(default='Test', max_length=200),
        ),
        migrations.AddField(
            model_name='membership',
            name='unit',
            field=models.CharField(default='Test', max_length=100),
        ),
    ]
