# Generated by Django 3.1.2 on 2020-11-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201103_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='membership',
            name='family_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='membership',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='membership',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='membership',
            name='receipt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='state',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='street_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='street_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='membership',
            name='suburb',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='membership',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
