# Generated by Django 3.1.2 on 2020-11-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20201103_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(default='test', max_length=15),
            preserve_default=False,
        ),
    ]
