# Generated by Django 3.1.2 on 2020-11-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_membership_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(max_length=30),
        ),
    ]
